name: Test
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        swift: [swift-DEVELOPMENT-SNAPSHOT-2021-11-12-a]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Swift
      uses: slashmo/install-swift@main
      with:
        version: ${{ matrix.swift }}

    - name: Checkout
      uses: actions/checkout@v2

      - name: Run Tests
      run: swift test --parallel
