name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Swift Toolchain
      id: swift-toolchain-cache
      uses: actions/cache@v2
      with:
        path: |
          /usr/share/swift-toolchain
        key: ${{ runner.os }}-${{ hashFiles('.swift-version') }}

    - name: Install Swift Toolchain
      run: ./scripts/install-swift.sh

    - name: Print Swift Version
      run: swift --version

    - name: Run Tests
      run: swift test --parallel
